"""
Seed 40 realistic demo submissions for the Young Minds LA school.

Usage:
    python manage.py seed_ymla_demo
    python manage.py seed_ymla_demo --force   # re-seed even if data exists

Idempotent by default: skips if YMLA already has >= 10 submissions.
created_at dates are back-dated to match each submission's status lifecycle.
"""
from __future__ import annotations

from datetime import datetime, timezone

from django.core.management.base import BaseCommand
from django.db import transaction

from core.models import School, Submission


# ---------------------------------------------------------------------------
# 40 high-quality demo submissions
# Distribution: 14×3yr | 12×4yr | 6×2yr | 4×tk_kinder | 4×parent_and_me
#               Venice 8 | West LA 12 | Westchester 20
#               New 16 | Tour Sched 10 | Tour Comp 6 | Enrolled 4 | Wait 2 | Declined 2
# ---------------------------------------------------------------------------
SUBMISSIONS = [
    # ── 3-YEAR PROGRAM (14) ──────────────────────────────────────────────
    {
        "data": {
            "student_first_name": "Emma", "student_last_name": "Rodriguez",
            "date_of_birth": "2022-09-15", "age": 3, "gender": "female",
            "interested_in": "3yr_program", "campus_preference": "venice",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Maria Rodriguez", "contact_email": "m.rodriguez.fam@gmail.com",
            "contact_phone": "310-555-2847", "guardian_relationship": "mother",
            "city": "Venice", "zip": "90291",
            "emergency_contact_name": "Carlos Rodriguez",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-3921",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "Emma loves arts and crafts and is very excited about starting school.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 5,
    },
    {
        "data": {
            "student_first_name": "Liam", "student_last_name": "Chen",
            "date_of_birth": "2022-11-08", "age": 3, "gender": "male",
            "interested_in": "3yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Jennifer Chen", "contact_email": "jennifer.chen.la@gmail.com",
            "contact_phone": "310-555-4162", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90025",
            "emergency_contact_name": "David Chen",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-5071",
            "allergies": "Peanut allergy — carries EpiPen", "medical_conditions": "None",
            "how_did_you_hear": "friend_family",
            "notes": "A close friend recommended YMLA. Looking forward to the tour.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 18,
    },
    {
        "data": {
            "student_first_name": "Sofia", "student_last_name": "Patel",
            "date_of_birth": "2022-07-29", "age": 3, "gender": "female",
            "interested_in": "3yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "extended_day",
            "guardian_name": "Priya Patel", "contact_email": "priya.patel84@gmail.com",
            "contact_phone": "424-555-7390", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Raj Patel",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-8201",
            "allergies": "Mild dairy sensitivity", "medical_conditions": "None",
            "how_did_you_hear": "instagram_facebook",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 3,
    },
    {
        "data": {
            "student_first_name": "Noah", "student_last_name": "Williams",
            "date_of_birth": "2022-10-22", "age": 3, "gender": "male",
            "interested_in": "3yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Sarah Williams", "contact_email": "swilliams.la2023@yahoo.com",
            "contact_phone": "310-555-6134", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Michael Williams",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-7245",
            "allergies": "Seasonal allergies, takes Zyrtec as needed",
            "medical_conditions": "None",
            "how_did_you_hear": "drove_by",
            "notes": "We drive past the Westchester campus every day — love the look of the school.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 22,
    },
    {
        "data": {
            "student_first_name": "Olivia", "student_last_name": "Kim",
            "date_of_birth": "2022-12-03", "age": 3, "gender": "female",
            "interested_in": "3yr_program", "campus_preference": "westla",
            "enrollment_type": "sibling", "desired_start_date": "fall_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Susan Kim", "contact_email": "susankim.westla@gmail.com",
            "contact_phone": "310-555-8374", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90064",
            "emergency_contact_name": "James Kim",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-9485",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "current_family",
            "notes": "Olivia's older brother attended West LA. We're excited to bring her too.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 7,
    },
    {
        "data": {
            "student_first_name": "Ethan", "student_last_name": "Johnson",
            "date_of_birth": "2022-08-17", "age": 3, "gender": "male",
            "interested_in": "3yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "flexible",
            "guardian_name": "Amanda Johnson", "contact_email": "amanda.j.family@gmail.com",
            "contact_phone": "323-555-1284", "guardian_relationship": "mother",
            "city": "Culver City", "zip": "90230",
            "emergency_contact_name": "Brian Johnson",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "323-555-2391",
            "allergies": "None",
            "medical_conditions": "Mild asthma, uses inhaler before vigorous outdoor play",
            "how_did_you_hear": "google",
            "notes": "We have flexible work schedules so any time slot would work for us.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 14,
    },
    {
        "data": {
            "student_first_name": "Ava", "student_last_name": "Martinez",
            "date_of_birth": "2022-05-04", "age": 3, "gender": "female",
            "interested_in": "3yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Rosa Martinez", "contact_email": "rosa.martinez2022@gmail.com",
            "contact_phone": "310-555-3047", "guardian_relationship": "mother",
            "city": "El Segundo", "zip": "90245",
            "emergency_contact_name": "Luis Martinez",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-4158",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "instagram_facebook",
            "notes": "We heard great things from neighbors who enrolled their daughter here.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 9,
    },
    {
        "data": {
            "student_first_name": "Mateo", "student_last_name": "Garcia",
            "date_of_birth": "2022-06-28", "age": 3, "gender": "male",
            "interested_in": "3yr_program", "campus_preference": "venice",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Elena Garcia", "contact_email": "elena.garcia.venice@gmail.com",
            "contact_phone": "310-555-5269", "guardian_relationship": "mother",
            "city": "Venice", "zip": "90291",
            "emergency_contact_name": "Roberto Garcia",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-6370",
            "allergies": "Tree nut allergy (mild)", "medical_conditions": "None",
            "how_did_you_hear": "friend_family",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Completed", "days_ago": 38,
    },
    {
        "data": {
            "student_first_name": "Isabella", "student_last_name": "Lopez",
            "date_of_birth": "2022-09-04", "age": 3, "gender": "female",
            "interested_in": "3yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "extended_day",
            "guardian_name": "Carmen Lopez", "contact_email": "c.lopez.family@gmail.com",
            "contact_phone": "310-555-7481", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90094",
            "emergency_contact_name": "Antonio Lopez",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-8592",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "drove_by",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 6,
    },
    {
        "data": {
            "student_first_name": "Mason", "student_last_name": "Thompson",
            "date_of_birth": "2022-10-16", "age": 3, "gender": "male",
            "interested_in": "3yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Kelly Thompson", "contact_email": "kellythompson.la@gmail.com",
            "contact_phone": "310-555-9603", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90025",
            "emergency_contact_name": "Greg Thompson",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-0714",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "Hoping for a morning slot — both parents work from home in the afternoon.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 26,
    },
    {
        "data": {
            "student_first_name": "Mia", "student_last_name": "Davis",
            "date_of_birth": "2022-07-05", "age": 3, "gender": "female",
            "interested_in": "3yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Nicole Davis", "contact_email": "ndavis.family23@gmail.com",
            "contact_phone": "424-555-1825", "guardian_relationship": "mother",
            "city": "Playa del Rey", "zip": "90293",
            "emergency_contact_name": "Mark Davis",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-2936",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "instagram_facebook",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 4,
    },
    {
        "data": {
            "student_first_name": "Jayden", "student_last_name": "Brown",
            "date_of_birth": "2022-08-30", "age": 3, "gender": "male",
            "interested_in": "3yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "asap",
            "preferred_time": "extended_day",
            "guardian_name": "Tanya Brown", "contact_email": "tanya.brown.westla@gmail.com",
            "contact_phone": "323-555-3047", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90064",
            "emergency_contact_name": "Marcus Brown",
            "emergency_contact_relationship": "Uncle",
            "emergency_contact_phone": "323-555-4158",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "Recently relocated from Chicago — looking to enroll as soon as a spot opens.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Completed", "days_ago": 32,
    },
    {
        "data": {
            "student_first_name": "Luna", "student_last_name": "Nguyen",
            "date_of_birth": "2022-11-25", "age": 3, "gender": "female",
            "interested_in": "3yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Lan Nguyen", "contact_email": "lan.nguyen.fam@gmail.com",
            "contact_phone": "310-555-5274", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Minh Nguyen",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-6385",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "friend_family",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 11,
    },
    {
        "data": {
            "student_first_name": "Elijah", "student_last_name": "Taylor",
            "date_of_birth": "2023-01-15", "age": 3, "gender": "male",
            "interested_in": "3yr_program", "campus_preference": "venice",
            "enrollment_type": "new_student", "desired_start_date": "spring_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Danielle Taylor", "contact_email": "dtaylor.family@gmail.com",
            "contact_phone": "310-555-7481", "guardian_relationship": "mother",
            "city": "Venice", "zip": "90291",
            "emergency_contact_name": "Marcus Taylor",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-8592",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "drove_by",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Enrolled", "days_ago": 72,
    },

    # ── 4-YEAR PROGRAM (12) ──────────────────────────────────────────────
    {
        "data": {
            "student_first_name": "Charlotte", "student_last_name": "Wilson",
            "date_of_birth": "2021-08-12", "age": 4, "gender": "female",
            "interested_in": "4yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Rachel Wilson", "contact_email": "rwilson.family@gmail.com",
            "contact_phone": "310-555-9603", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Tom Wilson",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-0714",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "Charlotte is very curious and loves science experiments at home.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 19,
    },
    {
        "data": {
            "student_first_name": "Oliver", "student_last_name": "Anderson",
            "date_of_birth": "2021-10-05", "age": 4, "gender": "male",
            "interested_in": "4yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "extended_day",
            "guardian_name": "Catherine Anderson", "contact_email": "c.anderson.family@gmail.com",
            "contact_phone": "310-555-1825", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90025",
            "emergency_contact_name": "Scott Anderson",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-2936",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "instagram_facebook",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 8,
    },
    {
        "data": {
            "student_first_name": "Amelia", "student_last_name": "Harris",
            "date_of_birth": "2021-06-19", "age": 4, "gender": "female",
            "interested_in": "4yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Patricia Harris", "contact_email": "pharris.fam@yahoo.com",
            "contact_phone": "424-555-3047", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90094",
            "emergency_contact_name": "Derek Harris",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-4158",
            "allergies": "Peanut allergy (carries EpiPen)", "medical_conditions": "None",
            "how_did_you_hear": "friend_family",
            "notes": "Amelia has been at a Montessori program and we'd like to try a different approach.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Completed", "days_ago": 44,
    },
    {
        "data": {
            "student_first_name": "Jackson", "student_last_name": "Lee",
            "date_of_birth": "2021-09-03", "age": 4, "gender": "male",
            "interested_in": "4yr_program", "campus_preference": "venice",
            "enrollment_type": "sibling", "desired_start_date": "spring_2026",
            "preferred_time": "morning",
            "guardian_name": "Linda Lee", "contact_email": "linda.lee.family@gmail.com",
            "contact_phone": "310-555-5269", "guardian_relationship": "mother",
            "city": "Venice", "zip": "90291",
            "emergency_contact_name": "Robert Lee",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-6370",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "current_family",
            "notes": "Jackson's cousin attends Venice. Very excited to join!",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Enrolled", "days_ago": 85,
    },
    {
        "data": {
            "student_first_name": "Aria", "student_last_name": "Clark",
            "date_of_birth": "2021-07-14", "age": 4, "gender": "female",
            "interested_in": "4yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "flexible",
            "guardian_name": "Michelle Clark", "contact_email": "michelle.clark.23@gmail.com",
            "contact_phone": "424-555-7481", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Kevin Clark",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-8592",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "drove_by",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 2,
    },
    {
        "data": {
            "student_first_name": "Sebastian", "student_last_name": "Lewis",
            "date_of_birth": "2021-11-22", "age": 4, "gender": "male",
            "interested_in": "4yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Diana Lewis", "contact_email": "dlewis.family@gmail.com",
            "contact_phone": "310-555-9603", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90064",
            "emergency_contact_name": "Christopher Lewis",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-0714",
            "allergies": "Dairy intolerance", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "We're hoping for a late-morning or lunch bunch slot if possible.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 20,
    },
    {
        "data": {
            "student_first_name": "Penelope", "student_last_name": "Walker",
            "date_of_birth": "2021-05-08", "age": 4, "gender": "female",
            "interested_in": "4yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Jessica Walker", "contact_email": "j.walker.fam@gmail.com",
            "contact_phone": "310-555-1825", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90094",
            "emergency_contact_name": "Daniel Walker",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-2936",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "instagram_facebook",
            "notes": "We know spots are limited — please keep us on the waitlist.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Waitlisted", "days_ago": 30,
    },
    {
        "data": {
            "student_first_name": "Aiden", "student_last_name": "Young",
            "date_of_birth": "2021-08-27", "age": 4, "gender": "male",
            "interested_in": "4yr_program", "campus_preference": "venice",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "extended_day",
            "guardian_name": "Lisa Young", "contact_email": "lisa.young.la@gmail.com",
            "contact_phone": "310-555-3047", "guardian_relationship": "mother",
            "city": "Venice", "zip": "90291",
            "emergency_contact_name": "Eric Young",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-4158",
            "allergies": "None",
            "medical_conditions": "Mild asthma, uses inhaler as needed",
            "how_did_you_hear": "friend_family",
            "notes": "Aiden is very active and thrives in structured outdoor environments.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 10,
    },
    {
        "data": {
            "student_first_name": "Chloe", "student_last_name": "King",
            "date_of_birth": "2021-10-14", "age": 4, "gender": "female",
            "interested_in": "4yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "asap",
            "preferred_time": "morning",
            "guardian_name": "Angela King", "contact_email": "angela.king.family@gmail.com",
            "contact_phone": "424-555-5269", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90025",
            "emergency_contact_name": "Harold King",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-6370",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Completed", "days_ago": 48,
    },
    {
        "data": {
            "student_first_name": "Lucas", "student_last_name": "Wright",
            "date_of_birth": "2021-06-07", "age": 4, "gender": "male",
            "interested_in": "4yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Stephanie Wright", "contact_email": "s.wright.fam@gmail.com",
            "contact_phone": "310-555-7481", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Nathan Wright",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-8592",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "yelp",
            "notes": "Saw great reviews on Yelp. Looking forward to seeing the campus.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 16,
    },
    {
        "data": {
            "student_first_name": "Lily", "student_last_name": "Scott",
            "date_of_birth": "2021-09-19", "age": 4, "gender": "female",
            "interested_in": "4yr_program", "campus_preference": "westchester",
            "enrollment_type": "sibling", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Karen Scott", "contact_email": "karen.scott.family@gmail.com",
            "contact_phone": "310-555-9603", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90094",
            "emergency_contact_name": "Paul Scott",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-0714",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "current_family",
            "notes": "Lily's older sister is in the 3-year program — would love to have them at the same campus.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 13,
    },
    {
        "data": {
            "student_first_name": "Elias", "student_last_name": "Green",
            "date_of_birth": "2021-07-31", "age": 4, "gender": "male",
            "interested_in": "4yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "extended_day",
            "guardian_name": "Vanessa Green", "contact_email": "v.green.la@gmail.com",
            "contact_phone": "323-555-1825", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90064",
            "emergency_contact_name": "Anthony Green",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "323-555-2936",
            "allergies": "Tree nut allergy", "medical_conditions": "None",
            "how_did_you_hear": "friend_family",
            "notes": "We'd ideally like the extended day program. Please keep us on the waitlist.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Waitlisted", "days_ago": 34,
    },

    # ── 2-YEAR PROGRAM (6) ───────────────────────────────────────────────
    {
        "data": {
            "student_first_name": "Zoey", "student_last_name": "Baker",
            "date_of_birth": "2023-08-05", "age": 2, "gender": "female",
            "interested_in": "2yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Megan Baker", "contact_email": "meganbaker.la@gmail.com",
            "contact_phone": "310-555-3047", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90025",
            "emergency_contact_name": "Chris Baker",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-4158",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "Zoey is our first child — we're excited to get her into a social setting early.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 12,
    },
    {
        "data": {
            "student_first_name": "Henry", "student_last_name": "Nelson",
            "date_of_birth": "2023-10-12", "age": 2, "gender": "male",
            "interested_in": "2yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Sandra Nelson", "contact_email": "snelson.family@gmail.com",
            "contact_phone": "424-555-5269", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "William Nelson",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-6370",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "drove_by",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 23,
    },
    {
        "data": {
            "student_first_name": "Nora", "student_last_name": "Carter",
            "date_of_birth": "2023-07-22", "age": 2, "gender": "female",
            "interested_in": "2yr_program", "campus_preference": "venice",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Bethany Carter", "contact_email": "bcarter.fam@gmail.com",
            "contact_phone": "310-555-7481", "guardian_relationship": "mother",
            "city": "Venice", "zip": "90291",
            "emergency_contact_name": "Jonathan Carter",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-8592",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "instagram_facebook",
            "notes": "Nora is very social for her age — we're looking for a small group environment.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 15,
    },
    {
        "data": {
            "student_first_name": "Samuel", "student_last_name": "Phillips",
            "date_of_birth": "2023-09-15", "age": 2, "gender": "male",
            "interested_in": "2yr_program", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "spring_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Christine Phillips", "contact_email": "c.phillips.family@gmail.com",
            "contact_phone": "310-555-9603", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90064",
            "emergency_contact_name": "David Phillips",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-0714",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "current_family",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Enrolled", "days_ago": 78,
    },
    {
        "data": {
            "student_first_name": "Victoria", "student_last_name": "Evans",
            "date_of_birth": "2023-06-30", "age": 2, "gender": "female",
            "interested_in": "2yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Katherine Evans", "contact_email": "k.evans.wchester@gmail.com",
            "contact_phone": "424-555-1825", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90094",
            "emergency_contact_name": "James Evans",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-2936",
            "allergies": "Egg allergy (mild)", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "We want to start her early to build social skills.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 1,
    },
    {
        "data": {
            "student_first_name": "Daniel", "student_last_name": "Turner",
            "date_of_birth": "2023-11-08", "age": 2, "gender": "male",
            "interested_in": "2yr_program", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Theresa Turner", "contact_email": "theresa.turner.23@gmail.com",
            "contact_phone": "310-555-3047", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Gary Turner",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-4158",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "We decided to go with a Montessori school closer to home.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Declined", "days_ago": 17,
    },

    # ── TK / KINDER (4) ─────────────────────────────────────────────────
    {
        "data": {
            "student_first_name": "Riley", "student_last_name": "Morris",
            "date_of_birth": "2020-07-14", "age": 5, "gender": "female",
            "interested_in": "tk_kinder", "campus_preference": "westla",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Sandra Morris", "contact_email": "smorris.family@gmail.com",
            "contact_phone": "310-555-5269", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90025",
            "emergency_contact_name": "Bruce Morris",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-6370",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "yelp",
            "notes": "We ultimately decided to go with the neighborhood public school's TK program.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Declined", "days_ago": 12,
    },
    {
        "data": {
            "student_first_name": "Julian", "student_last_name": "Collins",
            "date_of_birth": "2019-11-30", "age": 6, "gender": "male",
            "interested_in": "tk_kinder", "campus_preference": "venice",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning",
            "guardian_name": "Angela Collins", "contact_email": "angela.collins.la@gmail.com",
            "contact_phone": "310-555-7481", "guardian_relationship": "mother",
            "city": "Venice", "zip": "90292",
            "emergency_contact_name": "Patrick Collins",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-8592",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "friend_family",
            "notes": "Julian missed the district TK cutoff last year — exploring all Kinder options.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 25,
    },
    {
        "data": {
            "student_first_name": "Aurora", "student_last_name": "Stewart",
            "date_of_birth": "2020-09-05", "age": 5, "gender": "female",
            "interested_in": "tk_kinder", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "fall_2026",
            "preferred_time": "morning_lunch_bunch",
            "guardian_name": "Heather Stewart", "contact_email": "h.stewart.fam@gmail.com",
            "contact_phone": "424-555-9603", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Brian Stewart",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-0714",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Completed", "days_ago": 41,
    },
    {
        "data": {
            "student_first_name": "Caleb", "student_last_name": "Ramirez",
            "date_of_birth": "2020-06-20", "age": 5, "gender": "male",
            "interested_in": "tk_kinder", "campus_preference": "westchester",
            "enrollment_type": "returning_student", "desired_start_date": "spring_2026",
            "preferred_time": "morning",
            "guardian_name": "Monica Ramirez", "contact_email": "m.ramirez.fam@gmail.com",
            "contact_phone": "310-555-1825", "guardian_relationship": "mother",
            "city": "El Segundo", "zip": "90245",
            "emergency_contact_name": "Diego Ramirez",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-2936",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "drove_by",
            "notes": "Caleb is very ready for Kinder — we want to make sure he has a strong foundation.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Enrolled", "days_ago": 65,
    },

    # ── PARENT & ME (4) ──────────────────────────────────────────────────
    {
        "data": {
            "student_first_name": "Zara", "student_last_name": "Ahmed",
            "date_of_birth": "2025-01-15", "age": 1, "gender": "female",
            "interested_in": "parent_and_me", "campus_preference": "venice",
            "enrollment_type": "new_student", "desired_start_date": "asap",
            "preferred_time": "morning",
            "guardian_name": "Fatima Ahmed", "contact_email": "fatima.ahmed.la@gmail.com",
            "contact_phone": "310-555-3047", "guardian_relationship": "mother",
            "city": "Venice", "zip": "90291",
            "emergency_contact_name": "Omar Ahmed",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-4158",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "instagram_facebook",
            "notes": "Interested in the parent-and-me class to start building social connections early.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 3,
    },
    {
        "data": {
            "student_first_name": "Felix", "student_last_name": "Nakamura",
            "date_of_birth": "2023-12-10", "age": 2, "gender": "male",
            "interested_in": "parent_and_me", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "asap",
            "preferred_time": "morning",
            "guardian_name": "Yuki Nakamura", "contact_email": "yuki.nakamura.fam@gmail.com",
            "contact_phone": "424-555-5269", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90094",
            "emergency_contact_name": "Kenji Nakamura",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "424-555-6370",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "google",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Scheduled", "days_ago": 21,
    },
    {
        "data": {
            "student_first_name": "Stella", "student_last_name": "Okafor",
            "date_of_birth": "2024-08-22", "age": 1, "gender": "female",
            "interested_in": "parent_and_me", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "asap",
            "preferred_time": "morning",
            "guardian_name": "Ngozi Okafor", "contact_email": "ngozi.okafor.la@gmail.com",
            "contact_phone": "323-555-7481", "guardian_relationship": "mother",
            "city": "Los Angeles", "zip": "90064",
            "emergency_contact_name": "Chidi Okafor",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "323-555-8592",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "friend_family",
            "notes": "We want to start building early literacy and social skills.",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "Tour Completed", "days_ago": 35,
    },
    {
        "data": {
            "student_first_name": "Leo", "student_last_name": "Hernandez",
            "date_of_birth": "2024-03-07", "age": 2, "gender": "male",
            "interested_in": "parent_and_me", "campus_preference": "westchester",
            "enrollment_type": "new_student", "desired_start_date": "asap",
            "preferred_time": "morning",
            "guardian_name": "Carmen Hernandez", "contact_email": "carmen.hernandez.fam@gmail.com",
            "contact_phone": "310-555-9603", "guardian_relationship": "mother",
            "city": "Westchester", "zip": "90045",
            "emergency_contact_name": "Jorge Hernandez",
            "emergency_contact_relationship": "Father",
            "emergency_contact_phone": "310-555-0714",
            "allergies": "None", "medical_conditions": "None",
            "how_did_you_hear": "drove_by",
            "notes": "",
            "photo_release": True, "enrollment_agreement": True,
        },
        "status": "New", "days_ago": 8,
    },
]


class Command(BaseCommand):
    help = "Seeds 40 realistic demo submissions for the Young Minds LA school."

    def add_arguments(self, parser):
        parser.add_argument(
            "--force",
            action="store_true",
            help="Re-seed even if submissions already exist.",
        )

    @transaction.atomic
    def handle(self, *args, **opts):
        school = School.objects.filter(slug="young-minds-la").first()
        if not school:
            self.stdout.write(self.style.ERROR(
                "School 'young-minds-la' not found. "
                "Run migrations and ensure the school record exists first."
            ))
            return

        existing = Submission.objects.filter(school=school).count()
        if existing >= 10 and not opts["force"]:
            self.stdout.write(
                f"Skipping — {existing} submissions already exist for young-minds-la. "
                "Use --force to re-seed."
            )
            return

        now = datetime.now(tz=timezone.utc)
        created_count = 0

        for entry in SUBMISSIONS:
            sub = Submission.objects.create(
                school=school,
                form_key="default",
                data=entry["data"],
                status=entry["status"],
            )
            # Back-date created_at to match the submission lifecycle
            back_dated = now.replace(
                hour=9, minute=0, second=0, microsecond=0
            )
            from datetime import timedelta
            back_dated = back_dated - timedelta(days=entry["days_ago"])
            Submission.objects.filter(pk=sub.pk).update(created_at=back_dated)
            created_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Seeded {created_count} submissions for young-minds-la."
        ))
        self.stdout.write("Run: python manage.py seed_ymla_demo --force to reset.")
