services:
  - type: web
    name: student-enrollment-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py createcachetable --no-color 2>/dev/null; python manage.py migrate --noinput && python manage.py ensure_superuser && gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
        