# Generated by Django 6.0.1 on 2026-01-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('website_url', models.URLField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='')),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('theme_primary_color', models.CharField(blank=True, default='', max_length=20)),
                ('theme_accent_color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.school')),
            ],
        ),
    ]
