# Generated by Django 6.0.1 on 2026-02-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='form_key',
            field=models.CharField(db_index=True, default='default', help_text='Identifies which form was used, in case the school has multiple forms.', max_length=64),
        ),
    ]
