# Generated by Django 6.0.1 on 2026-02-04 02:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backfill_submission_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, default=core.models.generate_public_id, editable=False, max_length=16, unique=True, verbose_name='Application ID'),
        ),
    ]
