# Generated by Django 6.0.1 on 2026-02-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_submission_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(db_index=True, default='New', help_text='School-defined workflow status.', max_length=40),
        ),
    ]
