# Generated by Django 6.0.1 on 2026-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(db_index=True, default='New', max_length=40),
        ),
    ]
