# Generated by Django 6.0.1 on 2026-02-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='school',
            name='plan',
            field=models.CharField(blank=True, db_index=True, default='trial', max_length=32),
        ),
    ]
