# Generated by Django 6.0.1 on 2026-02-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_school_feature_flags_school_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='plan',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('starter', 'Starter'), ('pro', 'Pro'), ('growth', 'Growth')], db_index=True, default='trial', max_length=32),
        ),
    ]
