# Generated by ChatGPT — add Stripe cancellation scheduling fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_stripe_fields_to_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="stripe_cancel_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="stripe_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="stripe_cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
