# Generated by Django 6.0.1 on 2026-02-12 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_school_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.CreateModel(
            name='AdminPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('midnight', 'Midnight'), ('clean', 'Clean'), ('classic', 'Classic')], db_index=True, default='midnight', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Preference',
                'verbose_name_plural': 'Admin Preferences',
            },
        ),
    ]
