# Generated by Django 6.0.1 on 2026-02-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_adminpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpreference',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('clean', 'Clean'), ('minty', 'Minty')], db_index=True, default='midnight', max_length=32),
        ),
    ]
