# Generated by Django 6.0.1 on 2026-02-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_migrate_classic_to_minty'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='stripe_subscription_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
