# Generated by Django 6.0.1 on 2026-04-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds the Lead model.

    The four School billing fields (is_active, stripe_cancel_at, etc.) were
    already added to the database by migration 0017 via RunPython/raw SQL, but
    0017 used RunPython so Django's migration state doesn't know about them.
    We use SeparateDatabaseAndState here to update the state only — no DDL.
    """

    dependencies = [
        ('core', '0017_school_billing_lock_fields'),
    ]

    operations = [
        # ── Reconcile School billing fields (state-only; DB already has them) ──
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='school',
                    name='is_active',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='school',
                    name='stripe_cancel_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='school',
                    name='stripe_cancel_at_period_end',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='school',
                    name='stripe_current_period_end',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
            database_operations=[],  # 0017 already applied these via raw SQL
        ),
        # ── New Lead model ────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('normalized_email', models.EmailField(db_index=True, max_length=254)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('interested_in_label', models.CharField(blank=True, default='', max_length=200)),
                ('interested_in_value', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media'), ('walk_in', 'Walk-in'), ('event', 'Event'), ('other', 'Other')], default='website', max_length=50)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial_scheduled', 'Trial Scheduled'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], db_index=True, default='new', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=255)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='core.submission')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['school', 'status'], name='core_lead_school__1ed59e_idx'),
                    models.Index(fields=['school', 'normalized_email'], name='core_lead_school__7d3213_idx'),
                    models.Index(fields=['school', 'created_at'], name='core_lead_school__114ebd_idx'),
                    models.Index(fields=['school', 'next_follow_up_at'], name='core_lead_school__fbe116_idx'),
                    models.Index(fields=['school', 'status', 'next_follow_up_at'], name='core_lead_school__1e3c32_idx'),
                ],
            },
        ),
    ]
