# Generated by Django 6.0.1 on 2026-04-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_lead'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('school', 'normalized_email'), name='unique_lead_per_school_email'),
        ),
    ]
