# Generated by Django 6.0.1 on 2026-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_lead_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_summary',
            field=models.JSONField(blank=True, help_text="Claude-generated summary (dict with 'summary' and 'criteria_scores').", null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_summary_at',
            field=models.DateTimeField(blank=True, help_text='When the AI summary was last generated.', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media'), ('walk_in', 'Walk-in'), ('phone', 'Phone'), ('event', 'Event'), ('other', 'Other')], default='website', max_length=50),
        ),
    ]
