# Generated by Django 6.0.1 on 2026-04-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_draft_submission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='draftsubmission',
            new_name='core_drafts_token_69d635_idx',
            old_name='core_drafts_token_idx',
        ),
        migrations.RenameIndex(
            model_name='draftsubmission',
            new_name='core_drafts_token_e_7f34a4_idx',
            old_name='core_drafts_expires_idx',
        ),
        migrations.AddField(
            model_name='submission',
            name='school_submission_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('school', 'school_submission_number')},
        ),
    ]
