# Generated by Django 6.0.1 on 2026-04-28 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_backfill_trial_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsubmission',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_drafts', to='core.lead'),
        ),
    ]
