# Generated by Django 6.0.1 on 2026-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_submission_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media'), ('walk_in', 'Walk-in'), ('phone', 'Phone'), ('event', 'Event'), ('other', 'Other'), ('manual', 'Manual Entry')], default='website', max_length=50),
        ),
    ]
