# Generated by Django 6.0.1 on 2026-05-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_submission_followup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
