# Generated by Django 6.0.1 on 2026-05-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_school_add_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='app_fee_stripe_public_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='app_fee_stripe_secret_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='payment_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
