# Generated by Django 6.0.1 on 2026-06-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_schoolsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsession',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
