# Generated by Django 6.0.1 on 2026-07-06 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_lead_data_school_webhook_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media'), ('walk_in', 'Walk-in'), ('phone', 'Phone'), ('event', 'Event'), ('other', 'Other'), ('manual', 'Manual Entry'), ('website_lead_form', 'Lead Form'), ('webhook', 'Webhook')], default='website', max_length=50),
        ),
        migrations.CreateModel(
            name='DemoAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('pages_visited', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_tokens', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
