# Generated by Django 6.0.1 on 2026-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='activity_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
