# Generated by Django 6.0.1 on 2026-07-12 20:06

from django.db import migrations


def enable_tracking_for_demos(apps, schema_editor):
    School = apps.get_model("core", "School")
    School.objects.filter(is_demo=True).update(activity_tracking_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_school_activity_tracking'),
    ]

    operations = [
        migrations.RunPython(enable_tracking_for_demos, migrations.RunPython.noop),
    ]
