# Generated by Django 6.0.1 on 2026-07-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_school_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolemailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SchoolCustomToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=120)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tokens', to='core.school')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('school', 'key')},
            },
        ),
    ]
