# Generated by Django 6.0.1 on 2026-07-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_school_custom_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='smtp_from_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='plan',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('starter', 'Starter'), ('pro', 'Pro'), ('growth', 'Growth'), ('custom', 'Custom')], db_index=True, default='trial', max_length=32),
        ),
    ]
