# Generated by Django 6.0.1 on 2026-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_lead_form_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='default_follow_up_days',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
