# Generated by Django 6.0.1 on 2026-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_submission_schedule_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial_scheduled', 'Trial Scheduled'), ('trial_completed', 'Trial Completed'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], db_index=True, default='new', max_length=40),
        ),
    ]
