# Generated by Django 6.0.1 on 2026-07-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_trial_completed_lead_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lead",
            name="unique_lead_per_school_email",
        ),
    ]
