# Generated by Django 6.0.1 on 2026-07-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_lead_unique_email_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingchecklistitem',
            name='item',
            field=models.CharField(choices=[('school_created', 'School created'), ('plan_configured', 'Plan configured'), ('trial_configured', 'Trial configured'), ('admin_invited', 'Admin user invited'), ('team_access_configured', 'Team access configured'), ('branding_configured', 'Branding configured'), ('programs_configured', 'Programs configured'), ('workflows_configured', 'Enrollment workflows configured'), ('payment_configured', 'Payment workflow configured'), ('email_templates_reviewed', 'Email templates reviewed'), ('lead_capture_configured', 'Lead capture configured'), ('website_integration_complete', 'Website integration complete'), ('test_submission_completed', 'Test submission completed'), ('email_delivery_verified', 'Email delivery verified'), ('reports_verified', 'Reports verified'), ('school_marked_live', 'School marked Live')], max_length=50),
        ),
    ]
