# Generated by Django 6.0.1 on 2026-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_team_access_checklist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='config_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
