# Generated by Django 6.0.1 on 2026-08-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_seed_emily_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('cc_email', models.CharField(blank=True, default='', max_length=500)),
                ('include_leads', models.BooleanField(default=False)),
                ('include_submissions', models.BooleanField(default=False)),
                ('leads_filter', models.JSONField(default=dict)),
                ('submissions_filter', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='core.school')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('source', models.CharField(choices=[('lead', 'Lead'), ('submission', 'Submission')], max_length=16)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('merge_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='sent', max_length=16)),
                ('skipped_reason', models.CharField(blank=True, default='', max_length=200)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.broadcastmessage')),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
    ]
