# Generated by Django 6.0.1 on 2026-08-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='bcc_email',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
