# Generated by Codex on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_broadcast_add_bcc"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submit_fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
