# Generated by Django 6.0.1 on 2026-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_submission_submit_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='leads_notify_to_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='notification_bcc_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='notification_cc_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='notification_to_emails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
